services:  
  download-data:
    build:
      context: .
      dockerfile_inline: |
        FROM freqtradeorg/freqtrade:stable  
        USER root  
        RUN apt-get update && apt-get install -y git jq && rm -rf /var/lib/apt/lists/*
        RUN mkdir -p /freqtrade/user_data && chown -R ftuser:ftuser /freqtrade/user_data
        USER ftuser  
    container_name: download-market-data
    network_mode: host
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./tools:/freqtrade/tools"
      - "./configs:/freqtrade/configs"
    environment:
      - TZ=Asia/Shanghai
      - HTTP_PROXY=socks5://host.docker.internal:7897
      - HTTPS_PROXY=socks5://host.docker.internal:7897
    working_dir: /freqtrade
    # entrypoint: []
    # command: bash /freqtrade/tools/download-in-batches.sh
    # command: webserver
    command: >
      download-data 
      --timeframes 1m 5m 15m 1h 4h 
      --timerange 20230101-20251112
      --pairs BTC/USDT:USDT ETH/USDT:USDT XRP/USDT:USDT BNB/USDT:USDT SOL/USDT:USDT TRX/USDT:USDT DOGE/USDT:USDT ADA/USDT:USDT HYPE/USDT:USDT LINK/USDT:USDT BCH/USDT:USDT ZEC/USDT:USDT XLM/USDT:USDT XMR/USDT:USDT LTC/USDT:USDT SUI/USDT:USDT AVAX/USDT:USDT HBAR/USDT:USDT 1000SHIB/USDT:USDT TON/USDT:USDT DOT/USDT:USDT ICP/USDT:USDT M/USDT:USDT UNI/USDT:USDT NEAR/USDT:USDT TAO/USDT:USDT WLFI/USDT:USDT AAVE/USDT:USDT
      --prepend
      --config configs/trading_mode-${TRADING_MODE:-futures}.json
      --config configs/exampleconfig.json
      --config configs/pairlist-backtest-static-${EXCHANGE:-binance}-${TRADING_MODE:-futures}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json

  backtesting:
    image: freqtrade_with_numba
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: ${EXCHANGE:-binance}-${TRADING_MODE:-futures}-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX7}.py:/freqtrade/user_data/strategies/${STRATEGY_NAME:-NostalgiaForInfinityX7}.py"
    environment:
      COLUMNS: 240
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX7}
      --config configs/trading_mode-${TRADING_MODE:-futures}.json
      --timeframe-detail 1m 
      --cache none 
      --breakdown day
      --config configs/exampleconfig.json 
      --timerange ${TIMERANGE:-20230101-}
      --config configs/pairlist-backtest-static-${EXCHANGE:-binance}-${TRADING_MODE:-futures}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json
      --export signals 
      --export-filename user_data/backtest_results/${STRATEGY_NAME:-NostalgiaForInfinityX7}-${STRATEGY_VERSION:-latest}-${EXCHANGE:-binance}-${TRADING_MODE:-futures}-${TIMERANGE:-20230101-}.json
      --log-file user_data/logs/${STRATEGY_NAME:-NostalgiaForInfinityX7}-${STRATEGY_VERSION:-latest}-${EXCHANGE:-binance}-${TRADING_MODE:-futures}-${TIMERANGE:-20230101-}.log

  nfi-web-test:
    # image: freqtrade_with_numba
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    image: freqtradeorg/freqtrade:stable
    restart: always
    container_name: nfi-web-test
    environment:
      - TZ=Asia/Shanghai
    ports: ["8999:8080"]
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX7}.py:/freqtrade/user_data/strategies/${STRATEGY_NAME:-NostalgiaForInfinityX7}.py"
    command: >
      webserver
      --config configs/trading_mode-${TRADING_MODE:-futures}.json
      --config configs/exampleconfig_secret.json
      --config configs/pairlist-backtest-static-${EXCHANGE:-binance}-${TRADING_MODE:-futures}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json
